version: '3.1'
services:
  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    tty: true
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  # NGINX Service
  nginx:
    build: ./docker/nginx
    container_name: nginx
    privileged: true
    depends_on:
      - php
      - mariadb
      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    restart: unless-stopped
    tmpfs: /var/cache
    volumes:
      - ./wordpress:${APP_DOCROOT}
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
    env_file:
      - ./.env
  # PHP Service
  php:
    build: ./docker/php
    container_name: php
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./.env
    ports:
      - 9000:9000
    tmpfs:
      - /var/cache
    tty: true
    volumes:
      - ./wordpress:${APP_DOCROOT}
      # - /etc/letsencrypt/live/{{SERVER_HOSTNAME}}/fullchain.pem:/etc/letsencrypt/live/{{SERVER_HOSTNAME}}/fullchain.pem
      # - /etc/letsencrypt/live/{{SERVER_HOSTNAME}}/privkey.pem:/etc/letsencrypt/live/{{SERVER_HOSTNAME}}/privkey.pem
      # - /etc/letsencrypt/live/{{SERVER_HOSTNAME}}/chain.pem:/etc/letsencrypt/live/{{SERVER_HOSTNAME}}/chain.pem
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  # Redis Service
  redis:
    image: redis
    container_name: redis
    restart: always
  # Asset Watcher Service
  asset-watcher:
    build: ./docker/asset-watcher
    container_name: asset-watcher
    env_file:
      - ./.env
    tty: true
    volumes:
       - ./wordpress:${APP_DOCROOT}
volumes:
  mariadb_data:
    driver: local