version: '3.1'
services:
  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    tty: true
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  # NGINX Service
  nginx:
    build: ./docker/nginx
    container_name: nginx
    privileged: true
    depends_on:
      - php-fpm
      - mariadb
      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    restart: unless-stopped
    tmpfs: /var/cache
    volumes:
      - ./wordpress:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
    env_file:
      - ./.env
  # PHP-FPM Service
  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./.env
    ports:
      - 9000:9000
    tmpfs:
      - /var/cache
    tty: true
    volumes:
       - ./wordpress:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  # Redis Service
  redis:
    image: redis
    container_name: redis
    restart: always
volumes:
  mariadb_data:
    driver: local