#!/usr/bin/env bash

#---------------------------------------------------------------------
# download wordpress
#---------------------------------------------------------------------

function wordpress_cli_install() {

echo "================================================================="
echo "WordPress CLI Installer"
echo "================================================================="

cd ${APP_DOCROOT} || exit

curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/bin/wp

# Set the correct permissions on the files
chown -R www-data:www-data ${APP_DOCROOT}

}

#---------------------------------------------------------------------
# configure wordpress
#---------------------------------------------------------------------

function wordpress_config() {

echo "================================================================="
echo "WordPress Configuration"
echo "================================================================="

wp --allow-root core multisite-install --subdomains --url="https://${NGINX_SERVER_NAME}" --title="${NGINX_SERVER_NAME}" --admin_user="${WORDPRESS_ADMIN}" --admin_password="${WORDPRESS_ADMIN_PASSWORD}" --admin_email="${WORDPRESS_ADMIN_EMAIL}"

# better post structure as a default
wp --allow-root rewrite structure '/%postname%/' --hard

# install  plugin
# wp --allow-root plugin install amp antispam-bee nginx-helper wordpress-seo redis-cache --activate
# wp --allow-root theme install /usr/src/plugins/wordpress/theme.zip --activate

# We need to copy the object cache to the proper location
if [[ ! -f ${APP_DOCROOT}/wp-content/plugins/redis-cache/includes/object-cache.php ]]; then
echo "OK: No object cache file to copy"
else
cp ${APP_DOCROOT}/wp-content/plugins/redis-cache/includes/object-cache.php ${APP_DOCROOT}/wp-content/object-cache.php
fi

echo "================================================================="
echo "Installation is complete. Your username/password is listed below."
echo ""
echo "Username: ${WORDPRESS_ADMIN}"
echo "Password: ${WORDPRESS_ADMIN_PASSWORD}"
echo ""
echo "================================================================="

}

#---------------------------------------------------------------------
# clean up install activities
#---------------------------------------------------------------------

function cleanup () {

  find ${APP_DOCROOT} ! -user www-data -exec /usr/bin/env bash -c 'i="$1"; chown www-data:www-data "$i"' _ {} \;
  find ${APP_DOCROOT} ! -perm 755 -type d -exec /usr/bin/env bash -c 'i="$1"; chmod 755  "$i"' _ {} \;
  find ${APP_DOCROOT} ! -perm 644 -type f -exec /usr/bin/env bash -c 'i="$1"; chmod 644 "$i"' _ {} \;

  # Backup install page
  sleep 10
  # mv /usr/share/nginx/html/install.html /usr/share/nginx/html/$date-old-install.html
  # Clean the cache before launch
  rm -Rf /var/cache/*
}

#---------------------------------------------------------------------
# run wordpress install
#---------------------------------------------------------------------

function run() {
  if [[ -f ${APP_DOCROOT}/wp-config.php ]]; then
     wordpress_cli_install
     wordpress_config
    #  cleanup
  else
     echo "Wordpress is not installed, skipping setup..."
  fi

}

run

exit 0
